const mockTours = [
  {
    id: 1,
    name: "Tour Escalada en la Mojarra",
    description: "Disfruta de una emocionante aventura de escalada en uno de los destinos más hermosos.",
    category: "Escalada",
    image: "/assets/mojarra1.jpg",
  },
  {
    id: 2,
    name: "Senderismo en la Sierra Nevada",
    description: "Explora rutas panorámicas y disfruta de la naturaleza en su máxima expresión.",
    category: "Senderismo",
    image: "/assets/camping.jpeg",
  },
  {
    id: 3,
    name: "Caminata Nocturna en el Bosque",
    description: "Una experiencia única para observar la vida nocturna de la fauna.",
    category: "Aventura Nocturna",
    image: "/assets/equipo_escalada.jpg",
  },
  {
    id: 4,
    name: "Rafting en el Río Verde",
    description: "Atrévete a desafiar las corrientes en una emocionante expedición de rafting.",
    category: "Aventura Acuática",
    image: "/assets/mojarra2.jpg",
  },
  {
    id: 5,
    name: "Escalada en Rocas de La Muerte",
    description: "Desafía tus límites en un lugar famoso por sus impresionantes acantilados.",
    category: "Escalada",
    image: "/assets/mojarra3.jpg",
  },
  {
    id: 6,
    name: "Tour en Bicicleta por el Valle",
    description: "Recorre paisajes hermosos en un tour guiado en bicicleta.",
    category: "Ciclismo",
    image: "/assets/imagen1.jpg",
  },
  {
    id: 7,
    name: "Observación de Aves en el Humedal",
    description: "Descubre la diversidad aviar en un entorno natural único.",
    category: "Ecoturismo",
    image: "/assets/mojarra3.jpg",
  },
  {
    id: 8,
    name: "Campamento en la Playa",
    description: "Una experiencia de acampada junto al mar con actividades recreativas.",
    category: "Camping",
    image: "/assets/mojarra1.jpg",
  },
  {
    id: 9,
    name: "Escalada en Hielo en el Glaciar",
    description: "Una aventura invernal para los amantes de la escalada en hielo.",
    category: "Escalada",
    image: "/assets/mojarra2.jpg",
  },
  {
    id: 10,
    name: "Tour de Cueva y Espeleología",
    description: "Explora fascinantes formaciones geológicas en este tour de espeleología.",
    category: "Aventura",
    image: "/assets/camping.jpeg",
  },
  {
    id: 11,
    name: "Safari Fotográfico en la Selva",
    description: "Captura la belleza de la fauna y flora en un tour de fotografía.",
    category: "Fotografía",
    image: "/assets/camping.jpeg",
  },
  {
    id: 12,
    name: "Vía Ferrata en el Acantilado",
    description: "Una emocionante mezcla de escalada y senderismo en un entorno seguro.",
    category: "Escalada",
    image: "/assets/camping.jpeg",
  },
  {
    id: 13,
    name: "Kayak en el Lago Azul",
    description: "Navega en kayak por un lago tranquilo rodeado de naturaleza.",
    category: "Aventura Acuática",
    image: "/assets/camping.jpeg",
  },
  {
    id: 14,
    name: "Paseo a Caballo por la Montaña",
    description: "Disfruta de la belleza natural a lomos de un caballo en este tour guiado.",
    category: "Equitación",
    image: "/assets/camping.jpeg",
  },
  {
    id: 15,
    name: "Caminata de Observación de Estrellas",
    description: "Sumérgete en la magia de las estrellas en una caminata nocturna guiada.",
    category: "Aventura Nocturna",
    image: "/assets/camping.jpeg",
  },
];

export default mockTours;